services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8833:1433"
    restart: unless-stopped
